apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: p2p-devops-test
spec:
  destination:
    name: ''
    server: https://kubernetes.default.svc
  source:
    path: helm
    repoURL: git@github.com:draju1980/p2p-devops-test.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.staging.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
