---
apiVersion: v1
kind: Service
metadata:
  name: p2p-devops-test-svc
  namespace: p2p-devops-test
spec:
  selector:
    app: p2p-devops-test
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
