---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: p2p-devops-test-hpa
  namespace: p2p-devops-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: p2p-devops-test
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
