name: Golang Test, Lint, Format, Build, Publish Docker Image for p2p-devops-test

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test-lint-format:
    name: Test, Lint, and Format
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'
          cache: true

      - name: Install dependencies
        run: go mod tidy

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Lint code
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...

      - name: Format code
        run: gofmt -s -w .

  build-and-publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    needs: test-lint-format
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata for Docker image
      id: meta
      uses: docker/metadata-action@v1
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}
        
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
      
